/* 
 * @(#)FgwCm.java        1.0 09/12/14
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "hcta-epc", revision: "2014-09-18".
 */

package hctaEpc.fgw.statistics;

import Element;

import ElementChildrenIterator;

import Epc;

import General;

import JNCException;

import Procedure;

import UeConnect;

import UeRelease;

import com.tailf.jnc.YangElement;

/**
 * This class represents an element from 
 * the namespace http://hitachi-cta.com/ns/epc
 * generated to "src/hctaEpc/fgw/statistics/fgwCm"
 * <p>
 * See line 2445 in
 * oamPmServerCli.yang
 *
 * @version 1.0 2014-12-09
 * @author Auto Generated
 */
public class FgwCm extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for an empty FgwCm object.
     */
    public FgwCm() {
        super(Epc.NAMESPACE, "fgwCm");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public FgwCm clone() {
        return (FgwCm)cloneContent(new FgwCm());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public FgwCm cloneShallow() {
        return (FgwCm)cloneShallowContent(new FgwCm());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "general",
            "procedure",
            "ueConnect",
            "ueRelease",
        };
    }

    /* Access methods for list child: "general". */

    /**
     * Gets list entry "general", with specified keys.
     */
    public General getGeneral() throws JNCException {
        String path = "general";
        return (General)searchOne(path);
    }

    /**
     * Iterator method for the list "general".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator generalIterator() {
        return new ElementChildrenIterator(children, "general");
    }

    /**
     * Adds list entry "general", using an existing object.
     * @param general The object to add.
     * @return The added child.
     */
    public General addGeneral(General general) throws JNCException {
        insertChild(general, childrenNames());
        return general;
    }

    /**
     * Adds list entry "general".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public General addGeneral() throws JNCException {
        General general = new General();
        insertChild(general, childrenNames());
        return general;
    }

    /**
     * Deletes list entry "general", with specified keys.
     */
    public void deleteGeneral() throws JNCException {
        String path = "general";
        delete(path);
    }

    /* Access methods for list child: "procedure". */

    /**
     * Gets list entry "procedure", with specified keys.
     */
    public Procedure getProcedure() throws JNCException {
        String path = "procedure";
        return (Procedure)searchOne(path);
    }

    /**
     * Iterator method for the list "procedure".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator procedureIterator() {
        return new ElementChildrenIterator(children, "procedure");
    }

    /**
     * Adds list entry "procedure", using an existing object.
     * @param procedure The object to add.
     * @return The added child.
     */
    public Procedure addProcedure(Procedure procedure) throws JNCException {
        insertChild(procedure, childrenNames());
        return procedure;
    }

    /**
     * Adds list entry "procedure".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Procedure addProcedure() throws JNCException {
        Procedure procedure = new Procedure();
        insertChild(procedure, childrenNames());
        return procedure;
    }

    /**
     * Deletes list entry "procedure", with specified keys.
     */
    public void deleteProcedure() throws JNCException {
        String path = "procedure";
        delete(path);
    }

    /* Access methods for list child: "ueConnect". */

    /**
     * Gets list entry "ueConnect", with specified keys.
     */
    public UeConnect getUeConnect() throws JNCException {
        String path = "ueConnect";
        return (UeConnect)searchOne(path);
    }

    /**
     * Iterator method for the list "ueConnect".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator ueConnectIterator() {
        return new ElementChildrenIterator(children, "ueConnect");
    }

    /**
     * Adds list entry "ueConnect", using an existing object.
     * @param ueConnect The object to add.
     * @return The added child.
     */
    public UeConnect addUeConnect(UeConnect ueConnect) throws JNCException {
        insertChild(ueConnect, childrenNames());
        return ueConnect;
    }

    /**
     * Adds list entry "ueConnect".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public UeConnect addUeConnect() throws JNCException {
        UeConnect ueConnect = new UeConnect();
        insertChild(ueConnect, childrenNames());
        return ueConnect;
    }

    /**
     * Deletes list entry "ueConnect", with specified keys.
     */
    public void deleteUeConnect() throws JNCException {
        String path = "ueConnect";
        delete(path);
    }

    /* Access methods for list child: "ueRelease". */

    /**
     * Gets list entry "ueRelease", with specified keys.
     */
    public UeRelease getUeRelease() throws JNCException {
        String path = "ueRelease";
        return (UeRelease)searchOne(path);
    }

    /**
     * Iterator method for the list "ueRelease".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator ueReleaseIterator() {
        return new ElementChildrenIterator(children, "ueRelease");
    }

    /**
     * Adds list entry "ueRelease", using an existing object.
     * @param ueRelease The object to add.
     * @return The added child.
     */
    public UeRelease addUeRelease(UeRelease ueRelease) throws JNCException {
        insertChild(ueRelease, childrenNames());
        return ueRelease;
    }

    /**
     * Adds list entry "ueRelease".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public UeRelease addUeRelease() throws JNCException {
        UeRelease ueRelease = new UeRelease();
        insertChild(ueRelease, childrenNames());
        return ueRelease;
    }

    /**
     * Deletes list entry "ueRelease", with specified keys.
     */
    public void deleteUeRelease() throws JNCException {
        String path = "ueRelease";
        delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
