/* 
 * @(#)MmeS4.java        1.0 09/12/14
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "hcta-epc", revision: "2014-09-18".
 */

package hctaEpc.mmeSgsn.interface_;

import Element;

import Epc;

import JNCException;

import MmeS4If;

import NodeSet;

import com.tailf.jnc.YangElement;

/**
 * This class represents an element from 
 * the namespace http://hitachi-cta.com/ns/epc
 * generated to "src/hctaEpc/mmeSgsn/interface_/mme-s4"
 * <p>
 * See line 371 in
 * upmConfig.yang
 *
 * @version 1.0 2014-12-09
 * @author Auto Generated
 */
public class MmeS4 extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Field for child container "mme-s4-if".
     */
    public MmeS4If mmeS4If = null;

    /**
     * Constructor for an empty MmeS4 object.
     */
    public MmeS4() {
        super(Epc.NAMESPACE, "mme-s4");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public MmeS4 clone() {
        return (MmeS4)cloneContent(new MmeS4());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public MmeS4 cloneShallow() {
        return (MmeS4)cloneShallowContent(new MmeS4());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "mme-s4-if",
        };
    }

    /* Access methods for container child: "mme-s4-if". */

    /**
     * Adds container entry "mmeS4If", using an existing object.
     * @param mmeS4If The object to add.
     * @return The added child.
     */
    public MmeS4If addMmeS4If(MmeS4If mmeS4If) throws JNCException {
        this.mmeS4If = mmeS4If;
        insertChild(mmeS4If, childrenNames());
        return mmeS4If;
    }

    /**
     * Adds container entry "mmeS4If".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public MmeS4If addMmeS4If() throws JNCException {
        MmeS4If mmeS4If = new MmeS4If();
        this.mmeS4If = mmeS4If;
        insertChild(mmeS4If, childrenNames());
        return mmeS4If;
    }

    /**
     * Deletes container entry "mmeS4If".
     * @return An array of the deleted element nodes.
     */
    public NodeSet deleteMmeS4If() throws JNCException {
        this.mmeS4If = null;
        String path = "mme-s4-if";
        return delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
        if (child instanceof MmeS4If) mmeS4If = (MmeS4If)child;
    }

}
